name: flutter_launcher_icons
description: A package which simplifies the task of updating your Flutter app's launcher icon.
version: 0.14.3
maintainer: Mark O'Sullivan (@MarkOSullivan94)
homepage: https://github.com/fluttercommunity/flutter_launcher_icons
repository: https://github.com/fluttercommunity/flutter_launcher_icons/
issue_tracker: https://github.com/fluttercommunity/flutter_launcher_icons/issues

dependencies:
  args: ^2.5.0
  checked_yaml: ^2.0.3
  cli_util: ^0.4.1
  image: ^4.2.0
  json_annotation: ^4.9.0
  path: ^1.9.0
  yaml: ^3.1.2

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  # Needed by build_version
  build_runner: ^2.4.12
  # https://pub.dev/packages/build_version
  build_version: ^2.1.1
  json_serializable: ^6.8.0
  mockito: ^5.4.4
  test: ^1.25.8
  test_descriptor: ^2.0.1
