name: flutter_launcher_icons
description: A package which simplifies the task of updating your Flutter app's launcher icon.
version: 0.8.1
maintainer: Mark O'Sullivan (@MarkOSullivan94)
homepage: https://github.com/fluttercommunity/flutter_launcher_icons

dependencies:
  image: ^3.0.2
  args: ^1.6.0
  yaml: ^3.1.0
  path: ^1.7.0

environment:
  sdk: '>=2.3.0 <3.0.0'

dev_dependencies:
  test: ^1.16.5
